### ISSUE TITLE
code review day5

### ISSUE THREAD

**Issue by michaelli00** [j-jh/AdventOfCode2024#1]
https://github.com/j-jh/AdventOfCode2024/blob/realmain/Day5.java#L54-L67 couldn't we just add to invalidRows on line 56 and then return early. Then outside the for loop you add to validRows cuz at this point you know that it has to be a valid row. This will remove the need for the boolean on line 50 `isValidRow`

Any reason why you're creating a new set here https://github.com/j-jh/AdventOfCode2024/blob/realmain/Day5.java#L72 

Might be beyond scope but what if the input isn't in the correct format https://github.com/j-jh/AdventOfCode2024/blob/realmain/Day5.java#L85 and https://github.com/j-jh/AdventOfCode2024/blob/realmain/Day5.java#L94C15-L94C44

Should use try with resources https://github.com/j-jh/AdventOfCode2024/blob/realmain/Day5.java#L113-L115 https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html. This might be a new statement for you. Normally we would do try...catch...finally where we close the scanner in the finally block. If an error is thrown when reading the file think about why scanner.close() wouldn't be called in your current code

**Comment by j-jh** [comment]
1. Removed isValidRow boolean, instead break early when row is invalid. 
2. Removed extra set, instead iterate through currentRowNums to check if number exists in value of key.
3. Assuming input follows given test case file formatting for now...
4. If error is thrown after scanner is opened, scanner is never closed as previous scanner.close() line is unreachable. Replaced with try with resources block to automatically close scanner.

**Comment by j-jh** [comment]
1. Removed isValidRow boolean, instead break early when row is invalid. 
2. Removed extra set, instead iterate through currentRowNums to check if number exists in value of key.
3. Assuming input follows given test case file formatting for now...
4. If error is thrown after scanner is opened, scanner is never closed as previous scanner.close() line is unreachable. Replaced with try with resources block to automatically close scanner.
